name: chattts
channels:
  - nvidia/label/cuda-11.8.0
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - cuda-toolkit
  - cudatoolkit=11.8
  - python<3.12
  - pytorch=2.2.2
  - torchvision=0.17.2
  - torchaudio==2.2.2
  - cython
  - numpy<2.0.0
  - omegaconf~=2.3.0
  - pynini==2.1.5
  - tqdm 
  - einops
  - pip
  - pip:
    - vector_quantize_pytorch
    - transformers==4.41.1
    - vocos
    - IPython
    - gradio
    - python-dotenv
    - WeTextProcessing
    - nemo_text_processing